# Generated by Django 5.0 on 2023-12-29 09:46

import authaccounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('profile_picture', models.ImageField(default='profile_images/defaultprofile.png', upload_to=authaccounts.models.upload_to, verbose_name='Image')),
                ('email_verified', models.BooleanField(default=False)),
                ('verification_otp', models.PositiveBigIntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'others')], default='O', max_length=255, null=True)),
                ('date_of_birth', models.DateField(auto_now_add=True)),
                ('aboutmovieLife', models.TextField(null=True)),
                ('mobile', models.BigIntegerField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
